coverage:
  status:
    project:
      default:
        # basic
        target: 85%
        threshold: 3%
       # advanced settings
        branches: 
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
